#ifndef INPUTCHARACTERSCODE_H_INCLUDED
#define INPUTCHARACTERSCODE_H_INCLUDED

#define A_CHAR_CODE 65
#define a_CHAR_CODE 97
#define B_CHAR_CODE 66
#define b_CHAR_CODE 98
#define C_CHAR_CODE 67
#define c_CHAR_CODE 99
#define D_CHAR_CODE 68
#define d_CHAR_CODE 100
#define M_CHAR_CODE 77
#define m_CHAR_CODE 109
#define N_CHAR_CODE 78
#define n_CHAR_CODE 110
#define P_CHAR_CODE 80
#define p_CHAR_CODE 112
#define Q_CHAR_CODE 81
#define q_CHAR_CODE 113
#define S_CHAR_CODE 83
#define s_CHAR_CODE 115
#define V_CHAR_CODE 86
#define v_CHAR_CODE 118
#define W_CHAR_CODE 87
#define w_CHAR_CODE 119

#define TAB_CODE 9
#define DIRECTIONAL_KEYS 224
#define DIRECTIONAL_RIGHT 77
#define DIRECTIONAL_LEFT 75
#define DIRECTIONAL_UP 72
#define DIRECTIONAL_DOWN 80

#endif // INPUTCHARACTERSCODE_H_INCLUDED
