#ifndef MAPCOLORS_H_INCLUDED
#define MAPCOLORS_H_INCLUDED

#define WALL_COLOR 1
#define MOUSE_COLOR 15
#define MOUSE_DOG_COLOR 5
#define FOOD_COLOR 0
#define BONE_COLOR 0
#define CAT_COLOR 4
#define CAT_IMMORTAL_COLOR 2
#define DOOR_COLOR 6
#define EMPTY_COLOR 0

#define WALL_CH_COLOR 0
#define MOUSE_CH_COLOR 0
#define MOUSE_DOG_CH_COLOR 0
#define FOOD_CH_COLOR 14
#define BONE_CH_COLOR 8
#define CAT_CH_COLOR 0
#define CAT_IMMORTAL_CH_COLOR 0
#define DOOR_CH_COLOR 7
#define EMPTY_CH_COLOR 0

#define DEFAULT_ITEM_BG_COLOR 0

#endif // MAPCOLORS_H_INCLUDED
