#ifndef MAPDIMENSIONS_H_INCLUDED
#define MAPDIMENSIONS_H_INCLUDED

#define MAP_LINES 11
#define MAP_COLUMNS 27
#define MAP_ITEM_LENGTH 2
#define MAP_ITEM_HEIGHT 2
#define MAP_INIT_LINE 7
#define MAP_INIT_COLUMN 33

#endif // MAPDIMENSIONS_H_INCLUDED
