#ifndef MAPTIMERS_H_INCLUDED
#define MAPTIMERS_H_INCLUDED

#define WAIT_TIME_AFTER_PAUSE 3000
#define MENU_UPTADE_RATE 1000
#define UPTADE_RATE_WHEN_PAUSED 1000
#define DELAY_TO_GET_USER_INPUT 100

#endif // MAPTIMERS_H_INCLUDED
